### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by iamhasibrahman** [function61/sql2json#2]
Would the performance of sqltojson varry if runs outside of container? In other words, was hoping to hear thoughts on job that runs inside the container and deals with large data set

**Comment by joonas-fi** [comment]
I don't think it'd be an issue: http://stackoverflow.com/questions/21889053/what-is-the-runtime-performance-cost-of-a-docker-container

This operation will either probably be CPU or network bound, both for which the overhead of a (DB client) container should be negligible.

Generally, you shouldn't worry about performance beforehand. Just try it, and if there's a problem then find out where the bottleneck lies.

**Comment by joonas-fi** [comment]
I am closing this for now as it is a speculative issue.

If you run into Docker-related performance problems, feel free to comment and we'll re-open this issue.
