### ISSUE TITLE
Large data set 

### ISSUE THREAD

**Issue by iamhasibrahman** [function61/sql2json#3]
For table of size 3 tb, which needs to be extracted and move over the network to be ingested into target - we usually spend a table into chunk ( if date available, split by date.). Is it possible to use your program to pass sql statement?

**Comment by joonas-fi** [comment]
This is duplicate of #1. So no, custom SQL statement is not yet implemented.

**Comment by joonas-fi** [comment]
@iamhasibrahman: check the issue #1 - I just implemented support for custom SQL export query. I am closing this one as a duplicate.
